export const IndiaStates = [
  { gst: "12", name: "Arunachal Pradesh", code: "AR" },
  { gst: "18", name: "Assam", code: "AS" },
  { gst: "37", name: "Andhra Pradesh", code: "AD" },
  { gst: "35", name: "Andaman and Nicobar Islands", code: "AN" },
  { gst: "10", name: "Bihar", code: "BR" },
  { gst: "04", name: "Chandigarh", code: "CH" },
  { gst: "22", name: "Chhattisgarh", code: "CG" },
  { gst: "26", name: "Dadra-Nagar Haveli & Daman and Diu", code: "DH" },
  { gst: "07", name: "Delhi", code: "DL" },
  { gst: "30", name: "Goa", code: "GA" },
  { gst: "24", name: "Gujarat", code: "GJ" },
  { gst: "06", name: "Haryana", code: "HR" },
  { gst: "02", name: "Himachal Pradesh", code: "HP" },
  { gst: "01", name: "Jammu and Kashmir", code: "JK" },
  { gst: "20", name: "Jharkhand", code: "JH" },
  { gst: "29", name: "Karnataka", code: "KA" },
  { gst: "32", name: "Kerala", code: "KL" },
  { gst: "38", name: "Ladakh", code: "LA" },
  { gst: "31", name: "Lakshadweep", code: "LD" },
  { gst: "23", name: "Madhya Pradesh", code: "MP" },
  { gst: "27", name: "Maharashtra", code: "MH" },
  { gst: "14", name: "Manipur", code: "MN" },
  { gst: "17", name: "Meghalaya", code: "ML" },
  { gst: "15", name: "Mizoram", code: "MZ" },
  { gst: "13", name: "Nagaland", code: "NL" },
  { gst: "21", name: "Odisha", code: "OR" },
  { gst: "34", name: "Puducherry", code: "PY" },
  { gst: "03", name: "Punjab", code: "PB" },
  { gst: "08", name: "Rajasthan", code: "RJ" },
  { gst: "11", name: "Sikkim", code: "SK" },
  { gst: "33", name: "Tamil Nadu", code: "TN" },
  { gst: "36", name: "Telangana", code: "TS" },
  { gst: "16", name: "Tripura", code: "TR" },
  { gst: "09", name: "Uttar Pradesh", code: "UP" },
  { gst: "05", name: "Uttarakhand", code: "UK" },
  { gst: "19", name: "West Bengal", code: "WB" },
  { gst: "97", name: "Other Territory", code: "OT" },
  { gst: "99", name: "International", code: "INTERNATIONAL" },
]
